//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscCalc.Domain.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESCCALCEntities : DbContext
    {
        public ESCCALCEntities()
            : base("name=ESCCALCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MasterAdvanceParameter> MasterAdvanceParameters { get; set; }
        public virtual DbSet<MasterBrakeLoad> MasterBrakeLoads { get; set; }
        public virtual DbSet<MasterChainPitchFactorFatigue> MasterChainPitchFactorFatigues { get; set; }
        public virtual DbSet<MasterCountryType> MasterCountryTypes { get; set; }
        public virtual DbSet<MasterDriveSystemQuantity> MasterDriveSystemQuantities { get; set; }
        public virtual DbSet<MasterEnvironmentType> MasterEnvironmentTypes { get; set; }
        public virtual DbSet<MasterGearboxType> MasterGearboxTypes { get; set; }
        public virtual DbSet<MasterHandrailDriveType> MasterHandrailDriveTypes { get; set; }
        public virtual DbSet<MasterHandrailShapeType> MasterHandrailShapeTypes { get; set; }
        public virtual DbSet<MasterImpactCoefficient> MasterImpactCoefficients { get; set; }
        public virtual DbSet<MasterInclination> MasterInclinations { get; set; }
        public virtual DbSet<MasterMaxCapacity> MasterMaxCapacities { get; set; }
        public virtual DbSet<MasterNominalStepbandSpeed> MasterNominalStepbandSpeeds { get; set; }
        public virtual DbSet<MasterNominalStepWidth> MasterNominalStepWidths { get; set; }
        public virtual DbSet<MasterPowerSupply> MasterPowerSupplies { get; set; }
        public virtual DbSet<MasterProduct> MasterProducts { get; set; }
        public virtual DbSet<MasterProductRelease> MasterProductReleases { get; set; }
        public virtual DbSet<MasterRatedLoad> MasterRatedLoads { get; set; }
        public virtual DbSet<MasterReferenceStandardGearbox> MasterReferenceStandardGearboxes { get; set; }
        public virtual DbSet<MasterReferenceStandardHandrail> MasterReferenceStandardHandrails { get; set; }
        public virtual DbSet<MasterReferenceStandardStep> MasterReferenceStandardSteps { get; set; }
        public virtual DbSet<MasterReferenceStandardStepChain> MasterReferenceStandardStepChains { get; set; }
        public virtual DbSet<MasterReferenceStandardTrackSystem> MasterReferenceStandardTrackSystems { get; set; }
        public virtual DbSet<MasterRollerPitch> MasterRollerPitches { get; set; }
        public virtual DbSet<MasterSafetyFactorandPinPressure> MasterSafetyFactorandPinPressures { get; set; }
        public virtual DbSet<MasterSpeedFactor> MasterSpeedFactors { get; set; }
        public virtual DbSet<MasterSprocketTooth> MasterSprocketTeeth { get; set; }
        public virtual DbSet<MasterStepBandDriveType> MasterStepBandDriveTypes { get; set; }
        public virtual DbSet<MasterStepChainGuide> MasterStepChainGuides { get; set; }
        public virtual DbSet<MasterStepChainSize> MasterStepChainSizes { get; set; }
        public virtual DbSet<MasterStepChainType> MasterStepChainTypes { get; set; }
        public virtual DbSet<MasterStepMaterial> MasterStepMaterials { get; set; }
        public virtual DbSet<MasterStoppingDistance> MasterStoppingDistances { get; set; }
        public virtual DbSet<MasterStrandQuantity> MasterStrandQuantities { get; set; }
        public virtual DbSet<MasterTeethNumberFactor> MasterTeethNumberFactors { get; set; }
        public virtual DbSet<MasterTrussIntermediateSupport> MasterTrussIntermediateSupports { get; set; }
        public virtual DbSet<MasterTrussPackage> MasterTrussPackages { get; set; }
        public virtual DbSet<MasterWearingFactor> MasterWearingFactors { get; set; }
        public virtual DbSet<MasterWearingfactorGraph> MasterWearingfactorGraphs { get; set; }
        public virtual DbSet<TxnAdvanceParameter> TxnAdvanceParameters { get; set; }
        public virtual DbSet<TxnCase> TxnCases { get; set; }
        public virtual DbSet<TxnCaseNonStandardGearbox> TxnCaseNonStandardGearboxes { get; set; }
        public virtual DbSet<TxnCaseNonStandardHandrail> TxnCaseNonStandardHandrails { get; set; }
        public virtual DbSet<TxnCaseNonStandardStep> TxnCaseNonStandardSteps { get; set; }
        public virtual DbSet<TxnCaseNonStandardStepChain> TxnCaseNonStandardStepChains { get; set; }
        public virtual DbSet<TxnCaseNonStandardTrackSystem> TxnCaseNonStandardTrackSystems { get; set; }
        public virtual DbSet<TxnCaseVersion> TxnCaseVersions { get; set; }
        public virtual DbSet<TxnFinalCalcParameter> TxnFinalCalcParameters { get; set; }
        public virtual DbSet<TxnIntermediateParameter> TxnIntermediateParameters { get; set; }
        public virtual DbSet<TxnLoadProfile> TxnLoadProfiles { get; set; }
        public virtual DbSet<TxnReportOption> TxnReportOptions { get; set; }
    }
}
