//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscCalc.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterMaxCapacity
    {
        public int MaxCapacityId { get; set; }
        public Nullable<int> StepbandSpeedId { get; set; }
        public Nullable<int> StepWidthId { get; set; }
        public Nullable<int> Cmax { get; set; }
    
        public virtual MasterNominalStepbandSpeed MasterNominalStepbandSpeed { get; set; }
        public virtual MasterNominalStepWidth MasterNominalStepWidth { get; set; }
    }
}
