//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscCalc.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterProduct()
        {
            this.MasterProductReleases = new HashSet<MasterProductRelease>();
            this.MasterReferenceStandardGearboxes = new HashSet<MasterReferenceStandardGearbox>();
            this.MasterReferenceStandardHandrails = new HashSet<MasterReferenceStandardHandrail>();
            this.MasterReferenceStandardStepChains = new HashSet<MasterReferenceStandardStepChain>();
            this.MasterReferenceStandardTrackSystems = new HashSet<MasterReferenceStandardTrackSystem>();
            this.MasterStepChainGuides = new HashSet<MasterStepChainGuide>();
            this.MasterStepChainSizes = new HashSet<MasterStepChainSize>();
            this.TxnCaseNonStandardGearboxes = new HashSet<TxnCaseNonStandardGearbox>();
            this.TxnCaseNonStandardHandrails = new HashSet<TxnCaseNonStandardHandrail>();
            this.TxnCaseNonStandardStepChains = new HashSet<TxnCaseNonStandardStepChain>();
            this.TxnCaseNonStandardTrackSystems = new HashSet<TxnCaseNonStandardTrackSystem>();
            this.TxnCaseVersions = new HashSet<TxnCaseVersion>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public Nullable<float> LoadCoefficient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterProductRelease> MasterProductReleases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterReferenceStandardGearbox> MasterReferenceStandardGearboxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterReferenceStandardHandrail> MasterReferenceStandardHandrails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterReferenceStandardStepChain> MasterReferenceStandardStepChains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterReferenceStandardTrackSystem> MasterReferenceStandardTrackSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterStepChainGuide> MasterStepChainGuides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterStepChainSize> MasterStepChainSizes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnCaseNonStandardGearbox> TxnCaseNonStandardGearboxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnCaseNonStandardHandrail> TxnCaseNonStandardHandrails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnCaseNonStandardStepChain> TxnCaseNonStandardStepChains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnCaseNonStandardTrackSystem> TxnCaseNonStandardTrackSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnCaseVersion> TxnCaseVersions { get; set; }
    }
}
