//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscCalc.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterStepChainGuide
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterStepChainGuide()
        {
            this.MasterReferenceStandardTrackSystems = new HashSet<MasterReferenceStandardTrackSystem>();
            this.TxnCaseVersions = new HashSet<TxnCaseVersion>();
        }
    
        public int GuideId { get; set; }
        public string GuideName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Productid { get; set; }
    
        public virtual MasterProduct MasterProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterReferenceStandardTrackSystem> MasterReferenceStandardTrackSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnCaseVersion> TxnCaseVersions { get; set; }
    }
}
