//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscCalc.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterTrussPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterTrussPackage()
        {
            this.TxnCaseVersions = new HashSet<TxnCaseVersion>();
        }
    
        public int TrussPackageId { get; set; }
        public string TrussPackageName { get; set; }
        public string Description { get; set; }
        public Nullable<int> InclinationId { get; set; }
        public Nullable<int> UpperSteps { get; set; }
        public Nullable<int> LowerSteps { get; set; }
        public Nullable<float> TransitionRadiusUpper { get; set; }
        public Nullable<int> TransitionRadiusLower { get; set; }
    
        public virtual MasterInclination MasterInclination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnCaseVersion> TxnCaseVersions { get; set; }
    }
}
