//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscCalc.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterNominalStepWidth
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterNominalStepWidth()
        {
            this.MasterBrakeLoads = new HashSet<MasterBrakeLoad>();
            this.MasterMaxCapacities = new HashSet<MasterMaxCapacity>();
            this.MasterRatedLoads = new HashSet<MasterRatedLoad>();
            this.MasterReferenceStandardSteps = new HashSet<MasterReferenceStandardStep>();
        }
    
        public int StepWidthId { get; set; }
        public Nullable<int> StepWidth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterBrakeLoad> MasterBrakeLoads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterMaxCapacity> MasterMaxCapacities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterRatedLoad> MasterRatedLoads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterReferenceStandardStep> MasterReferenceStandardSteps { get; set; }
    }
}
