//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscCalc.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterTrussIntermediateSupport
    {
        public int TrussIntermediateSupportId { get; set; }
        public Nullable<int> TrussIntermediateSupportNumber { get; set; }
        public string Description { get; set; }
        public Nullable<int> MinSpan { get; set; }
        public Nullable<int> MaxSpan { get; set; }
    }
}
