//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscCalc.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterSafetyFactorandPinPressure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterSafetyFactorandPinPressure()
        {
            this.TxnCaseVersions = new HashSet<TxnCaseVersion>();
        }
    
        public int SafetyFactorandPinPressureId { get; set; }
        public string Description { get; set; }
        public Nullable<int> SafetyFactor { get; set; }
        public Nullable<int> PinPressureId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnCaseVersion> TxnCaseVersions { get; set; }
    }
}
