//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscCalc.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterProductRelease
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterProductRelease()
        {
            this.MasterReferenceStandardGearboxes = new HashSet<MasterReferenceStandardGearbox>();
            this.MasterReferenceStandardHandrails = new HashSet<MasterReferenceStandardHandrail>();
            this.MasterReferenceStandardSteps = new HashSet<MasterReferenceStandardStep>();
            this.MasterReferenceStandardStepChains = new HashSet<MasterReferenceStandardStepChain>();
            this.MasterReferenceStandardTrackSystems = new HashSet<MasterReferenceStandardTrackSystem>();
            this.TxnCaseVersions = new HashSet<TxnCaseVersion>();
        }
    
        public int ProductReleaseId { get; set; }
        public Nullable<float> Name { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual MasterProduct MasterProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterReferenceStandardGearbox> MasterReferenceStandardGearboxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterReferenceStandardHandrail> MasterReferenceStandardHandrails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterReferenceStandardStep> MasterReferenceStandardSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterReferenceStandardStepChain> MasterReferenceStandardStepChains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterReferenceStandardTrackSystem> MasterReferenceStandardTrackSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnCaseVersion> TxnCaseVersions { get; set; }
    }
}
