//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscCalc.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxnCaseNonStandardStepChain
    {
        public int NonStandardStepChainId { get; set; }
        public Nullable<int> CaseVersionId { get; set; }
        public string StepChainName { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<float> DeadWeightOfStepChain { get; set; }
        public Nullable<float> ChainPitch { get; set; }
        public Nullable<float> ChainRollerPitch { get; set; }
        public Nullable<float> DeadWeightOfConnection { get; set; }
        public Nullable<float> BreakeLoad { get; set; }
        public Nullable<float> LinkArea { get; set; }
        public Nullable<bool> IsBlueComponent { get; set; }
        public Nullable<bool> IsTempConfig { get; set; }
        public string Comment { get; set; }
    
        public virtual MasterProduct MasterProduct { get; set; }
        public virtual TxnCaseVersion TxnCaseVersion { get; set; }
    }
}
