//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscCalc.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxnCaseVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TxnCaseVersion()
        {
            this.TxnCaseNonStandardGearboxes = new HashSet<TxnCaseNonStandardGearbox>();
            this.TxnCaseNonStandardHandrails = new HashSet<TxnCaseNonStandardHandrail>();
            this.TxnCaseNonStandardSteps = new HashSet<TxnCaseNonStandardStep>();
            this.TxnCaseNonStandardStepChains = new HashSet<TxnCaseNonStandardStepChain>();
            this.TxnCaseNonStandardTrackSystems = new HashSet<TxnCaseNonStandardTrackSystem>();
            this.TxnFinalCalcParameters = new HashSet<TxnFinalCalcParameter>();
            this.TxnIntermediateParameters = new HashSet<TxnIntermediateParameter>();
            this.TxnLoadProfiles = new HashSet<TxnLoadProfile>();
            this.TxnReportOptions = new HashSet<TxnReportOption>();
        }
    
        public int CaseVersionId { get; set; }
        public Nullable<int> CaseId { get; set; }
        public Nullable<int> VersionNumber { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductReleaseId { get; set; }
        public Nullable<float> VerticalRise { get; set; }
        public Nullable<int> TrussPackageId { get; set; }
        public Nullable<int> StepChainGuideId { get; set; }
        public Nullable<int> TrussUpperExtensionLength { get; set; }
        public Nullable<int> TrussLowerExtensionLength { get; set; }
        public Nullable<float> HorizontalNoOfStepsUpper { get; set; }
        public Nullable<float> HorizontalNoOfStepsLower { get; set; }
        public Nullable<float> TransitionRadiusUpperPassenger { get; set; }
        public Nullable<float> TranstionRadiusLowerPassenger { get; set; }
        public Nullable<float> TransitionRadiusUpperBackTrack { get; set; }
        public Nullable<float> TranstionRadiusLowerBackTrack { get; set; }
        public Nullable<int> StepBandTypeId { get; set; }
        public Nullable<int> StepChainTypeId { get; set; }
        public Nullable<int> StepChainConditionId { get; set; }
        public Nullable<int> SafetyFactorandPinPressureId { get; set; }
        public Nullable<int> DestinationCountryId { get; set; }
        public Nullable<int> EscalatorEnvironmentId { get; set; }
        public Nullable<int> PowerSupplyId { get; set; }
        public Nullable<int> GearBoxTypeId { get; set; }
        public Nullable<int> MainDriveStrandQuantityId { get; set; }
        public Nullable<int> LoadTypeId { get; set; }
        public Nullable<int> MainDriveChainConditionId { get; set; }
        public Nullable<float> SafetyFactor { get; set; }
        public Nullable<int> HandrailTypeId { get; set; }
        public Nullable<int> HandrailDriveTypeId { get; set; }
        public Nullable<bool> IsAdvanceParam { get; set; }
        public Nullable<bool> IsCustomStep { get; set; }
        public Nullable<bool> IsCustomStepChain { get; set; }
        public Nullable<bool> IsCustomTrackSystem { get; set; }
        public Nullable<bool> IsCustomGearbox { get; set; }
        public Nullable<bool> IsCustomHandrail { get; set; }
        public Nullable<bool> IsFreezed { get; set; }
        public string Report { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsEditable { get; set; }
        public string Comments { get; set; }
        public string Project { get; set; }
        public Nullable<int> StepWidth { get; set; }
        public Nullable<float> StepbandSpeed { get; set; }
        public Nullable<float> Inclination { get; set; }
    
        public virtual MasterCountryType MasterCountryType { get; set; }
        public virtual MasterEnvironmentType MasterEnvironmentType { get; set; }
        public virtual MasterGearboxType MasterGearboxType { get; set; }
        public virtual MasterHandrailDriveType MasterHandrailDriveType { get; set; }
        public virtual MasterHandrailShapeType MasterHandrailShapeType { get; set; }
        public virtual MasterImpactCoefficient MasterImpactCoefficient { get; set; }
        public virtual MasterPowerSupply MasterPowerSupply { get; set; }
        public virtual MasterProduct MasterProduct { get; set; }
        public virtual MasterProductRelease MasterProductRelease { get; set; }
        public virtual MasterSafetyFactorandPinPressure MasterSafetyFactorandPinPressure { get; set; }
        public virtual MasterStepChainGuide MasterStepChainGuide { get; set; }
        public virtual MasterStepChainType MasterStepChainType { get; set; }
        public virtual MasterStepMaterial MasterStepMaterial { get; set; }
        public virtual MasterStrandQuantity MasterStrandQuantity { get; set; }
        public virtual MasterTrussPackage MasterTrussPackage { get; set; }
        public virtual MasterWearingFactor MasterWearingFactor { get; set; }
        public virtual MasterWearingFactor MasterWearingFactor1 { get; set; }
        public virtual TxnCase TxnCase { get; set; }
        public virtual TxnCase TxnCase1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnCaseNonStandardGearbox> TxnCaseNonStandardGearboxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnCaseNonStandardHandrail> TxnCaseNonStandardHandrails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnCaseNonStandardStep> TxnCaseNonStandardSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnCaseNonStandardStepChain> TxnCaseNonStandardStepChains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnCaseNonStandardTrackSystem> TxnCaseNonStandardTrackSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnFinalCalcParameter> TxnFinalCalcParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnIntermediateParameter> TxnIntermediateParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnLoadProfile> TxnLoadProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TxnReportOption> TxnReportOptions { get; set; }
    }
}
