//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscCalc.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxnCaseNonStandardStep
    {
        public int NonStandardStepId { get; set; }
        public Nullable<int> CaseVersionId { get; set; }
        public string StepWidthName { get; set; }
        public Nullable<int> StepMaterialId { get; set; }
        public Nullable<float> DeadWeightOfStepAssembly { get; set; }
        public Nullable<float> StepPitch { get; set; }
        public Nullable<float> HorizontalDistanceOfChainRollerToBalancePointOfStepAssembly { get; set; }
        public Nullable<float> DistanceChainRollerToStepRoller { get; set; }
        public Nullable<float> HorizontalDistanceOfChainRollerToStepRoller { get; set; }
        public Nullable<float> StepAngle { get; set; }
        public Nullable<bool> IsBlueComponent { get; set; }
        public Nullable<bool> IsTempConfig { get; set; }
        public string Comment { get; set; }
    
        public virtual MasterStepMaterial MasterStepMaterial { get; set; }
        public virtual TxnCaseVersion TxnCaseVersion { get; set; }
    }
}
