//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscCalc.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxnFinalCalcParameter
    {
        public int CalculationId { get; set; }
        public Nullable<int> CaseVersionId { get; set; }
        public Nullable<float> MotorPower { get; set; }
        public Nullable<float> Deceleration { get; set; }
        public Nullable<float> SafetyFactorDriveChain { get; set; }
        public Nullable<float> SafetyFactorGearBox { get; set; }
        public Nullable<float> ChainLinkSurfacePressure { get; set; }
        public Nullable<float> StepLoad { get; set; }
        public Nullable<float> PassengerStepLoad { get; set; }
        public Nullable<float> BrakeTimeWithoutBrakeIncidenceTime { get; set; }
        public Nullable<float> BrakeTimeWithBrakeIncidenceTime { get; set; }
        public Nullable<float> TorqueGearBoxOutputShaft { get; set; }
        public Nullable<float> TorqueMainShaft { get; set; }
        public Nullable<float> ChainRollerForceNorToTrack { get; set; }
        public Nullable<float> ChainRollerTrackSupportForce { get; set; }
        public Nullable<float> StepRollerForceNorToTrack { get; set; }
        public Nullable<float> TotalDeflection { get; set; }
        public Nullable<float> SafetyFactorYielding { get; set; }
        public Nullable<float> PassengerSideChainRollerLoad { get; set; }
        public Nullable<float> PassengerSideStepRollerLoad { get; set; }
        public Nullable<float> SafetyFactor { get; set; }
        public Nullable<float> PinPressure { get; set; }
        public Nullable<float> TotalChainLifeTimeElongation { get; set; }
        public Nullable<float> Forces1 { get; set; }
        public Nullable<float> Forces2 { get; set; }
        public Nullable<float> StaticSafetyFactor { get; set; }
        public Nullable<float> ReactionForceStepChainRoller { get; set; }
        public Nullable<float> ReactionForcesChainLinkDirection { get; set; }
        public Nullable<float> ResultantBearingForce { get; set; }
        public Nullable<float> NominalLifeTime10 { get; set; }
        public Nullable<float> NominalLifeTimeH { get; set; }
        public Nullable<float> DynamicChainLoad { get; set; }
        public Nullable<float> LoadCycles { get; set; }
        public Nullable<float> FatigueLife { get; set; }
    
        public virtual TxnCaseVersion TxnCaseVersion { get; set; }
    }
}
