//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscCalc.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxnIntermediateParameter
    {
        public int IntermidiateId { get; set; }
        public Nullable<int> CaseVersionId { get; set; }
        public Nullable<float> ProjectedStepDepth { get; set; }
        public Nullable<float> ProjectedStepSurfaceArea { get; set; }
        public Nullable<float> StepDepth { get; set; }
        public Nullable<float> StepHeight { get; set; }
        public Nullable<float> DeadLoadStepChain { get; set; }
        public Nullable<float> DeadLoadSingleStep { get; set; }
        public Nullable<float> TotalNumberOfHorizontalSteps { get; set; }
        public Nullable<float> LiftingPower { get; set; }
        public Nullable<float> PowerLossCausedByHandrailFriction { get; set; }
        public Nullable<float> PowerLossOfStepBandInHorizontalArea { get; set; }
        public Nullable<float> powerLossOfStepBandInInclineArea { get; set; }
        public Nullable<float> EffectiveDiameterOfStepChainSprocket { get; set; }
        public Nullable<float> ChainDriveRatio { get; set; }
        public Nullable<float> HandrailDriveRatioMainshaftHandrailshaft { get; set; }
        public Nullable<float> HandrailDriveRatioHandrailshaftJackshaft { get; set; }
        public Nullable<float> HandrailDriveRatioJackshaftNewelend { get; set; }
        public Nullable<float> RotationSpeedOfGearBoxOutputShaft { get; set; }
        public Nullable<float> RotationSpeedOfMainShaft_ { get; set; }
        public Nullable<float> StepBandChainSpeed { get; set; }
        public Nullable<float> HandrailSpeed { get; set; }
        public Nullable<float> RotationSpeedOfNewelEndDriveWheel { get; set; }
        public Nullable<float> RatioBetweenMainAndHandrailShaft { get; set; }
        public Nullable<float> RotationSpeedOfJackShaft_ { get; set; }
        public Nullable<float> RotationSpeedOfHandrailShaft { get; set; }
        public Nullable<float> BendingMoment_ { get; set; }
        public Nullable<float> ReactionLoadAtCenterSupport { get; set; }
        public Nullable<float> ReactionLoadAtLowerHeadSupport { get; set; }
        public Nullable<float> ReactionLoadAtUpperHeadSupport { get; set; }
        public Nullable<float> BrakeDistanceExcludingBrakeIncidenceTime { get; set; }
        public Nullable<float> BrakeDistanceIncludingBrakeIncidenceTime { get; set; }
        public Nullable<float> DecelerationTorque { get; set; }
        public Nullable<float> MomentOfInertiaOfEmptyEscalator { get; set; }
        public Nullable<float> MomentOfInertiaOfEscalatorAtMotorShaft { get; set; }
        public Nullable<float> MomentOfInertiaOfFullLoadedEscalator { get; set; }
        public Nullable<float> PathOfStepBandDuringBrakeIncidenceTime { get; set; }
        public Nullable<float> PathOfStepBandDuringTimet2 { get; set; }
        public Nullable<float> RequiredTorqueToHoldTheBrakeLoad { get; set; }
        public Nullable<float> StepBandSpeedAfterRise { get; set; }
        public Nullable<float> TensileForceCausedByBrakeLoad { get; set; }
        public Nullable<float> TensileForceCausedByDeadLoadOfStepBand { get; set; }
        public Nullable<float> TimeToDecelerateRotationSpeedRise { get; set; }
        public Nullable<float> TorqueAtMotorShaftCausedByBrakeLoad { get; set; }
        public Nullable<float> BotalBreakLoad { get; set; }
        public Nullable<float> TotalMomentOfInertiaAtMotorShaft { get; set; }
        public Nullable<float> TotalTensileForce { get; set; }
        public Nullable<float> TotalRatioBetweenMainShaftAndMotorShaftSpeed { get; set; }
        public Nullable<float> TotalEfficiencyOfGearBoxAndChainDrive { get; set; }
        public Nullable<float> RotationSpeedRiseDuringIncidenceTime { get; set; }
        public Nullable<float> DownhillSlopeForceCausedByRatedLoad { get; set; }
        public Nullable<float> StepBandFrictionForceInHorizontalArea { get; set; }
        public Nullable<float> StepBandFrictionForceInInclineArea { get; set; }
        public Nullable<float> TorqueAtMainShaftCausedByHandrailFriction { get; set; }
        public Nullable<float> TorqueMainShaftCausedByStepBand { get; set; }
        public Nullable<float> EffectiveMainShaftDriveChainSprocketDiameter { get; set; }
        public Nullable<float> RatioBetweenMainShaftAndGearBoxOutput { get; set; }
        public Nullable<float> TorqueAtMainShaftCausedByStepBandFrictionInclineArea { get; set; }
        public Nullable<float> TorqueMainShaftCausedByStepBandInHorizontalArea { get; set; }
        public Nullable<float> EquivalentPassengerLoad { get; set; }
        public Nullable<float> RequiredTorqueToLiftEquivalentPassengerLoad { get; set; }
        public Nullable<float> EquivalentStepLoad { get; set; }
        public Nullable<float> DistanceChainRollerToStepRollerBackTrack { get; set; }
        public Nullable<float> HorizontalDistanceChainRollerToBalancePointOfStepBackTrack { get; set; }
        public Nullable<float> VerticalChainRollerForce { get; set; }
        public Nullable<float> VerticalStepRollerForce { get; set; }
        public Nullable<float> StepRollerForceNormalToTrack { get; set; }
        public Nullable<float> DistanceRollerToSupport { get; set; }
        public Nullable<float> DeflectionCausedByFSR1 { get; set; }
        public Nullable<float> DeflectionCausedByFSR2 { get; set; }
        public Nullable<float> DeflectionCausedByFSR3 { get; set; }
        public Nullable<float> RollerReactionForceCausedByStepLoad { get; set; }
        public Nullable<float> DistanceBetweenPassengerAndRoller { get; set; }
        public Nullable<float> SupportForces { get; set; }
        public Nullable<float> RollerForceNormalToTrack { get; set; }
        public Nullable<float> BendingStress { get; set; }
        public Nullable<float> MaximumBendingMoment { get; set; }
        public Nullable<float> QuantityOfStepsSupportedByOnePairOfBrackets { get; set; }
        public Nullable<float> ChainRollerForceNormalToTrack { get; set; }
        public Nullable<float> ChainTensionCausedByStepLoad { get; set; }
        public Nullable<float> EstimatedChainLifeTime { get; set; }
        public Nullable<float> ChainTensionCausedByStepLoadBrakeLoad { get; set; }
        public Nullable<float> NumberOfTeeth { get; set; }
        public Nullable<float> MaximumAcceptableElongation { get; set; }
        public Nullable<float> TotalNumberOfChainLinks { get; set; }
        public Nullable<float> Angle1 { get; set; }
        public Nullable<float> Angle2 { get; set; }
        public Nullable<float> Angle3 { get; set; }
        public Nullable<float> TensileForceInStepChainAtUpperTransitionCurve { get; set; }
        public Nullable<float> BackTrackTransitionRadius { get; set; }
        public Nullable<float> VerticalStepRollerForcesAppliedHorizontalArea { get; set; }
        public Nullable<float> VerticalChainRollerForcesAppliedInHorizontalArea { get; set; }
        public Nullable<float> StepRollerForcesAppliedNormalToTrackInInclineArea { get; set; }
        public Nullable<float> ChainRollerForcesAppliedNormalToTrackInInclineArea { get; set; }
        public Nullable<float> StepRollerForceAppliedBackTrackInHorizontalArea { get; set; }
        public Nullable<float> ChainRolleForceAppliedBackTrackInHorizontalArea { get; set; }
        public Nullable<float> VerticalStepRolleForcesAppliedBackTrackInInclineArea { get; set; }
        public Nullable<float> VerticalChainRollerForcesAppliedBackTrackInInclineArea { get; set; }
        public Nullable<float> TotalStepChainRollerLoad { get; set; }
        public Nullable<float> ResultantForceWhichNeedsSupportedByStepChainRoller { get; set; }
        public Nullable<float> AngleInUpperTransitionCurve { get; set; }
        public Nullable<float> AngleOfPressureOnSprocket { get; set; }
        public Nullable<float> AngleOnSprocket { get; set; }
        public Nullable<float> PositionAngleOfFirstRoller { get; set; }
        public Nullable<float> StepChainSprocketPitchAngle { get; set; }
        public Nullable<float> HorizontalBearingForce { get; set; }
        public Nullable<float> VerticalBearingForce { get; set; }
        public Nullable<float> MaximumHorizontalHandrailTensileForce { get; set; }
        public Nullable<float> MaximumVerticalHandrailTensileForce { get; set; }
        public Nullable<float> MinimumHorizontalHandrailTensileForce { get; set; }
        public Nullable<float> MinimumVerticalHandrailTensileForce { get; set; }
        public Nullable<float> HorizontalHandrailDriveChainForce { get; set; }
        public Nullable<float> VerticalHandrailDriveChainForce { get; set; }
        public Nullable<float> HorizontalRadialHandrailDriveWheelForce { get; set; }
        public Nullable<float> VerticalRadialHandrailDriveWheelForce { get; set; }
        public Nullable<float> MaximumHandrailTensileForce { get; set; }
        public Nullable<float> RotationSpeedOfBearing { get; set; }
        public Nullable<float> HandrailPowerToDriveHandrail { get; set; }
        public Nullable<float> StaticHandrailSafetyRFactorAgainstBreaking { get; set; }
        public Nullable<float> RotationSpeedOfStepChainSprocketAndBearings { get; set; }
        public Nullable<float> ResultantForce { get; set; }
        public Nullable<float> HandrailDriveChainSpeed { get; set; }
        public Nullable<float> TorqueMainShaft { get; set; }
        public Nullable<float> StepChainTensionPassengerSide { get; set; }
        public Nullable<float> RadialForceCausedByHandrailDriveChainTension { get; set; }
        public Nullable<float> StepChainTensionBackTrack { get; set; }
        public Nullable<float> VerticalRadialForceCausedByMainDriveChainTension { get; set; }
        public Nullable<float> EffectiveDiameterOfHandrailDriveSprocket { get; set; }
        public Nullable<float> EffectiveRadiusOfMainDriveSprocketOnMainShaft { get; set; }
        public Nullable<float> EffectiveRadiusOfStepChainSprocketOnMainShaft { get; set; }
        public Nullable<float> EffectiveDiameterChainSprocketOnHandrailShaft { get; set; }
        public Nullable<float> EffectiveDiameterHandrailDriveWheel { get; set; }
        public Nullable<float> RadialForceCausedByHandrailDragForceDownRunningHorizontal { get; set; }
        public Nullable<float> RadialForceCausedByHandrailDragForceUpRunning_Horizontal { get; set; }
        public Nullable<float> TotalForcesCausedByHandrailDriveWheelupDownRunningHorizontal { get; set; }
        public Nullable<float> RadialForceCausedByHandrailDragForceRunningHorizontal { get; set; }
        public Nullable<float> RadialForcesCausedByRollerBeltHorizontal { get; set; }
        public Nullable<float> RadialForcesCausedByRollerBeltVertical { get; set; }
        public Nullable<float> TorqueDistributionHandrailShaft { get; set; }
        public Nullable<float> EquivalentLoad { get; set; }
        public Nullable<float> RotationSpeed { get; set; }
        public Nullable<float> PowerTransferredMyMainDriveChain { get; set; }
    
        public virtual TxnCaseVersion TxnCaseVersion { get; set; }
    }
}
