//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscCalc.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxnReportOption
    {
        public int ReportId { get; set; }
        public Nullable<int> CaseVersionId { get; set; }
        public Nullable<bool> FillInputParam { get; set; }
        public Nullable<bool> FillIntermediateParam { get; set; }
        public Nullable<bool> FillNonSTDParam { get; set; }
        public Nullable<bool> FillAdvanceParam { get; set; }
        public Nullable<bool> IsReportGenerated { get; set; }
    
        public virtual TxnCaseVersion TxnCaseVersion { get; set; }
    }
}
